SELECT B.NAME AS DEPARTMENT, A.NAME AS EMPLOYEE, A.SALARY AS SALARY FROM EMPLOYEE A LEFT JOIN DEPARTMENT B ON A.DEPARTMENTID = B.ID WHERE (A.DEPARTMENTID, A.SALARY) IN (SELECT DEPARTMENTID, MAX(SALARY) SAL FROM EMPLOYEE GROUP BY DEPARTMENTID);

